#
# Authors: Nuno Antunes <nmsa@dei.uc.pt>, João Antunes <jcfa@dei.uc.pt>
#

from python:3.11-alpine

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev openssl

RUN pip install flask==3.0.0

RUN pip install flask-wtf

RUN pip install psycopg2-binary

RUN pip install argon2-cffi

RUN pip install python-dotenv

RUN pip install Flask-SQLAlchemy

copy . /app

volume ["/app"]

workdir /app

run mkdir -p logs

EXPOSE 5000

CMD ["gunicorn","-b", "0.0.0.0:5000", "app:app"]